### PR TITLE
Remove support for logging out parameters

### PR DESCRIPTION
**Pull request by muzfuz**
See https://github.com/markburns/delfos/issues/9

This PR begins the work of  removing code that logs out arguments passed to a method call.

### CODE REVIEW

**Comment by muzfuz** [comment]
@markburns there are still three failing tests in this branch at the moment.  If you have a second I'd appreciate another pair of eyes.  Hope I haven't borked anything 🤣

**Comment by markburns** [comment]
Actually the approach I was thinking was to remove BasicObject patching. But we can try this as a first step

**Comment by muzfuz** [comment]
Yeah I think there's a lot more to be done -- I was thinking of just making a small initial change before ripping out the rest of it.  

That said, if you don't mind having a relatively big PR then I can go ahead with the rest of the work in this branch.

I'm still not sure how to fix the failing integration specs unfortunately, so I might do some refactoring in that area as well.

**Comment by markburns** [comment]
@muzfuz - Hey just fixed two. looking at the other

**Comment by muzfuz** [comment]
Nice work @markburns thanks for sorting that.

**Comment by markburns** [comment]
You're a collaborator now. So feel free to merge if you think it's ready

**Comment by muzfuz** [comment]
Great.  I'll go ahead and merge -- will work on the next removal step in a separate branch.

**Pull request merged**
